### ISSUE TITLE
Overall flow of DG

### ISSUE THREAD

**Issue by slightlyharp** [AY2223S2-CS2113-W15-2/tp#136]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/60395825/228519482-7ff1816a-6b70-4a34-ac46-83ed520fe219.png">
You might want to consider split your design into design and implementation as suggested on the course website. In this way some of the sequence diagram can be combined and it is easier for another developer to understand the full design. Especially for front end section as some of the sequence diagram seem like adding on /alt block of the previous section which can be put in the same section for easy reference

**Comment by jinxuan-owyong** [comment]
Developer guide has been updated in #261.
