### ISSUE TITLE
Sequence diagram for parser

### ISSUE THREAD

**Issue by slightlyharp** [AY2223S2-CS2113-W15-2/tp#137]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/60395825/228522628-c3a8e5e4-ed00-4fb4-83c4-03d4a90ab611.png">
I assume this is just calling constructor with "new AddCommand()" hence no need to add description as it might be mistaken as having a method call create

**Comment by adenteo** [comment]
The sequence diagram has been updated to reflect new changes. This issue will be closed.
