### ISSUE TITLE
Class diagram for frontend parser

### ISSUE THREAD

**Issue by slightlyharp** [AY2223S2-CS2113-W15-2/tp#138]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/60395825/228525439-2741d665-53b9-4090-b8ac-aea426a7b839.png">
Consider having a more detailed class diagram for the whole front end with the UI and frontend class.

**Comment by adenteo** [comment]
The class diagram has been updated to reflect new changes. This issue will be closed.
