### ISSUE TITLE
[PE-D][Tester D] random letter that is not within a flag

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-2/tp#158]
![Screenshot 2023-03-31 at 4.47.21 PM.png](https://raw.githubusercontent.com/mitchmalvin1/ped/main/files/6dbc69b6-a692-499b-9905-b41adb3d97ea.png)

for example, i added a random "d" inside and the program does not tell me that it is not supposed to have that. In this case it doesnt even act as extra description since it comes before the -d flag

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: mitchmalvin1/ped#1

**Comment by adenteo** [comment]
Will either

1) Raise error to user that they are mutually exclusive.
2) Inform user in UG and help menu that only the first arguments will be read.

**Comment by jinxuan-owyong** [comment]
The user guide has been updated and this issue will be closed.
