### ISSUE TITLE
[PE-D][Tester A] Displaying the list without any input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-2/tp#169]
Able to display the entry without any input

![image.png](https://raw.githubusercontent.com/SebastianSoewanto/ped/main/files/2afe2aaa-6b3a-47b4-9f43-0bef63febc9d.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: SebastianSoewanto/ped#1

**Comment by adenteo** [comment]
Probably require mandatory input when user uses these arguments.

**Comment by jinxuan-owyong** [comment]
The user guide has been updated and this issue will be closed.
