### ISSUE TITLE
[PE-D][Tester B] Case-sensitivity of Category

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-2/tp#172]
`category` is not case sensitive, however it is not documented int he UG also.
 
![image.png](https://raw.githubusercontent.com/alexgoexercise/ped/main/files/6f5bf1f6-32ee-41c8-bf67-429d44100a76.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: alexgoexercise/ped#5

**Comment by jinxuan-owyong** [comment]
The user guide has been updated and this issue will be closed.
