### ISSUE TITLE
[PE-D][Tester D] empty sd and ed for expense viewing

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-2/tp#177]
![Screenshot 2023-03-31 at 5.19.02 PM.png](https://raw.githubusercontent.com/mitchmalvin1/ped/main/files/7de689a7-8265-4fb8-a0ce-bae477bfd129.png)

empty sd and ed is still treated as view all even though it is not mentioned in the user guide. This is probably unintended.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: mitchmalvin1/ped#8

**Comment by jinxuan-owyong** [comment]
This issue has been fixed in https://github.com/AY2223S2-CS2113-W15-2/tp/pull/217. However, this still requires future documentation and will remain open until the user and developer guides are updated.

**Comment by jinxuan-owyong** [comment]
The user guide has been updated and this issue will be closed.
