### ISSUE TITLE
[PE-D][Tester D] program gives unexpected result when given large number for price

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-2/tp#191]
![Screenshot 2023-03-31 at 5.38.37 PM.png](https://raw.githubusercontent.com/mitchmalvin1/ped/main/files/55270bdb-9011-4852-abd3-dbe046156b89.png)

If the program cannot handle large number, it should at least mention in the user guide or warn the user in the program through exceptions

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: mitchmalvin1/ped#12

**Comment by jinxuan-owyong** [comment]
This issue is out of date and is superseded by the fix in https://github.com/AY2223S2-CS2113-W15-2/tp/pull/217 and will be closed.
