### ISSUE TITLE
review: latest tp jar file

### ISSUE THREAD

**Issue by nghochi123** [AY2223S2-CS2113-W15-2/tp#212]
1. Multiple values for description, category and price can be inputted, but only the first will be taken into account (#162, #166, #183)
![image](https://user-images.githubusercontent.com/35862661/229968975-274eb562-fd3e-45de-8118-3b08491cd1fd.png)

2. Income is being displayed as a positive expense (#181, #144; potentially fixed by #155)
![image](https://user-images.githubusercontent.com/35862661/229969110-4554fbcd-91e7-4b15-9663-52e3b3de58eb.png)

3. Price function not working for view with high expenditures (#186, #191, #196; potentially fixed by #210)
![image](https://user-images.githubusercontent.com/35862661/229969737-8a14bef4-7781-4a70-a8ba-4f9371cbb2c4.png)

4. Rounding error (#171)
![image](https://user-images.githubusercontent.com/35862661/229970044-83ec3451-6a6d-420c-b234-4d22001cee9d.png)

5. Case sensitivity of category might need to be added into documentation

**Comment by jinxuan-owyong** [comment]
All issues raised have been addressed and this issue will be closed.
