### ISSUE TITLE
Use severe logging level for unexpected events

### ISSUE THREAD

**Issue by jinxuan-owyong** [AY2223S2-CS2113-W15-2/tp#53]
I noticed the use of `Level.SEVERE` in `ParserTest.java`. It should be reserved for critical events, and should be used sparingly. In the two instances where `Level.SEVERE` was used, the application is able to recover on its own. I believe that a logging level of `warning` is sufficient.

__References__:
- https://commons.apache.org/proper/commons-logging/guide.html#Message_PrioritiesLevels
- https://www.javatpoint.com/java-logger

**Comment by adenteo** [comment]
@jinxuan-owyong Noted on this. Will make the necessary amendments on next integration.

**Comment by adenteo** [comment]
Fixed in #57
